version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
#      - cluster.name=es-docker-cluster
#      - bootstrap.memory_lock=true
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch.yml
#      - data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
#    networks:
#      - elastic

volumes:
  elasticsearch-data:
    driver: local

#networks:
#  elastic:
#    driver: bridge